const { Schema, model } = require('mongoose');

const songSchema = new Schema(
  {
    ID: { type: String },
    Title: { type: String },
    Seq: { type: Number },
    Rate: { type: Number },
    Length: { type: String },
    MusicKey: { type: String },
    BPM: { type: Number },
    BPMExact: { type: String },
    BPMF: { type: Number },
    Grid: { type: String },
    Meter: { type: String },
    ATune: { type: Number },
    PBRhythm: { type: Number },
    PBSpeed: { type: Number },
    PBMood: { type: Number },
    PBExperimental: { type: Number },
    PBOrganic: { type: Number },
    Stems: { type: String },
    Description: { type: String },
    Genre: { type: String },
    SubGenreA: { type: String },
    SubGenreB: { type: String },
    PrimaryMood: { type: String },
    SecondaryMoods: { type: String },
    Instruments: { type: String },
    Tags: { type: String },
    Changes: { type: String },
    ShapeArc: { type: String },
    SimilarPBTracks: { type: String },
    SimilarArtists: { type: String },
    CatNum: { type: String },
    ArtistName: { type: String },
    AlbumTitle: { type: String },
    FeatArtist: { type: String },
    Writers: { type: String },
    ISRCCode: { type: String },
    ISWCCode: { type: String },
    BandcampAlbumId: { type: String },
    BandcampTrackId: { type: String },
    BandcampURL: { type: String },
    SoundcloudURL: { type: String },
    SoundCloudId: { type: String },
    SpotifyURL: { type: String },
    AppleMusicURL: { type: String },
    DeezerURL: { type: String },
    TidalURL: { type: String },
    VimeoURL: { type: String },
    YoutubeURL: { type: String },
    Use: { type: String },
    Tools: { type: String },
    converted: { type: String }
},
  { timestamps: true },
);

module.exports = model('song', songSchema);
